version: '3.5'

x-ccache: &ccache
  CCACHE_COMPILERCHECK: content
  CCACHE_COMPRESS: 1
  CCACHE_COMPRESSLEVEL: 5
  CCACHE_MAXSIZE: 2G
  CCACHE_DIR: /ccache

services:
  builder:
    image: ${IMAGE_REPO}/knowhere-env:${IMAGE_ARCH}-${OS_NAME}-${DATE_VERSION}
    # Build devcontainer
    build:
      context: .
      dockerfile: ci/docker/builder/cpu/${OS_NAME}/Dockerfile
      cache_from:
        - ${IMAGE_REPO}/knowhere-env:${IMAGE_ARCH}-${OS_NAME}-${LATEST_DATE_VERSION}
    # user: {{ CURRENT_ID }}
    shm_size: 2G
    environment:
      <<: *ccache
      CUSTOM_THIRDPARTY_PATH: /tmp/thirdparty
    volumes: &builder-volumes
      - .:/go/src/github.com/milvus-io/knowhere:delegated
      - ${DOCKER_VOLUME_DIRECTORY:-.docker}/${IMAGE_ARCH}-${OS_NAME}-ccache:/ccache:delegated
      - ${DOCKER_VOLUME_DIRECTORY:-.docker}/${IMAGE_ARCH}-${OS_NAME}-go-mod:/go/pkg/mod:delegated
      - ${DOCKER_VOLUME_DIRECTORY:-.docker}/thirdparty:/tmp/thirdparty:delegated
      - ${DOCKER_VOLUME_DIRECTORY:-.docker}/${IMAGE_ARCH}-${OS_NAME}-vscode-extensions:/home/knowhere/.vscode-server/extensions:delegated
    working_dir: "/go/src/github.com/milvus-io/knowhere"
    # Command
    command: &builder-command >
      /bin/bash -c "
        make check-proto-product && make verifiers && make unittest"

networks:
  default:
    name: milvus_dev
