apiVersion: v1
kind: Pod
metadata:
  labels:
    app: publish
    componet: docker
spec:
  containers:
  - name: publish-images
    image: registry.zilliz.com/library/docker:v1.1.0
    imagePullPolicy: Always
    securityContext:
      privileged: true
    command:
    - cat
    tty: true
    resources:
      limits:
        memory: "8Gi"
        cpu: "2"
      requests:
        memory: "2Gi"
        cpu: "1"
    volumeMounts:
    - name: docker-sock
      mountPath: /var/run/docker.sock
  volumes:
  - name: docker-sock
    hostPath:
      path: /var/run/docker.sock
  tolerations:
  - key: dedicated
    operator: Equal
    value: milvus
    effect: NoSchedule
