apiVersion: v1
kind: Pod
metadata:
  name: milvus-cpu-build-env
  labels:
    app: milvus
    componet: cpu-build-env
spec:
  containers:
  - name: milvus-cpu-build-env
    image: registry.zilliz.com/milvus/milvus-cpu-build-env:v0.10.2-centos7
    env:
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    - name: OS_NAME
      value: "centos7"
    - name: BUILD_ENV_IMAGE_ID
      value: "702c1cc48b65115de5172b3267deccb65b82bcfd6129cad0ad4a0a33a3882b23"
    command:
    - cat
    tty: true
    resources:
      limits:
        memory: "24Gi"
        cpu: "10.0"
      requests:
        memory: "8Gi"
        cpu: "4.0"
  tolerations:
  - key: dedicated
    operator: Equal
    value: milvus
    effect: NoSchedule
