apiVersion: v1
kind: Pod
metadata:
  labels:
    app: milvus
    componet: test-env
spec:
  containers:
  - name: milvus-test-env
    image: registry.zilliz.com/milvus/milvus-test-env:v0.3
    command:
    - cat
    tty: true
    resources:
      limits:
        memory: "8Gi"
        cpu: "4.0"
      requests:
        memory: "4Gi"
        cpu: "2.0"
    volumeMounts:
    - name: kubeconf
      mountPath: /root/.kube/
      readOnly: true
  volumes:
  - name: kubeconf
    secret:
      secretName: test-cluster-config
  tolerations:
  - key: dedicated
    operator: Equal
    value: milvus
    effect: NoSchedule
