apiVersion: v1
kind: Pod
metadata:
  namespace: jenkins
spec:
  tolerations:
    - key: node-role.kubernetes.io/knowhere
      operator: Equal
      effect: NoSchedule
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - knowhere-e2e
          topologyKey: "kubernetes.io/hostname"
  containers:
  - name: kaniko
    imagePullPolicy: IfNotPresent
    image: harbor.milvus.io/devops/kaniko-executor:v1.8.0-debug
    command:
    - /busybox/cat
    tty: true
    volumeMounts:
      - name: kaniko-secret
        mountPath: /kaniko/.docker/
  volumes:
    - name: kaniko-secret
      secret:
        secretName: kaniko-secret-dockerhub
        items:
          - key: .dockerconfigjson
            path: config.json
  nodeSelector:
    app: knowhere
