apiVersion: v1
kind: Pod
metadata:
  labels:
    app: knowhere-ci
  namespace: knowhere-ci
spec:
  enableServiceLinks: false
  nodeSelector:
    app: knowhere
  containers:
  - name: main
    image: milvusdb/knowhere-env:amd64-ubuntu20.04-20220706-bb704b6
    tty: true
    args: ["cat"]
    resources:
      limits:
        memory: "64Gi"
        cpu: "12.0"
      requests:
        memory: "64Gi"
        cpu: "12.0"
    volumeMounts:
    - mountPath: /home/data
      name: db-data
  volumes:
    - name: db-data
      nfs:
        server: 172.16.70.239
        path: /qa
