apiVersion: v1
kind: Pod
metadata:
  labels:
    app: knowhere-e2e
  namespace: knowhere-ci
spec:
  enableServiceLinks: false
  nodeSelector:
    app: knowhere
  tolerations:
    - key: node-role.kubernetes.io/knowhere
      operator: Equal
      effect: NoSchedule
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - knowhere-e2e
          topologyKey: "kubernetes.io/hostname"
  containers:
  - name: build
    image: milvusdb/knowhere-gpu-build:amd64-ubuntu20.04-20230320-fa11e7b
    tty: true
    args: ["cat"]
  - name: main
    image: nvidia/cuda:11.6.0-runtime-ubuntu20.04
    tty: true
    args: ["cat"]
    resources:
      requests:
        nvidia.com/gpu: 1
        memory: "30Gi"
        cpu: "8"
      limits:
        nvidia.com/gpu: 1
        memory: "30Gi"
        cpu: "8"
    volumeMounts:
      - mountPath: /home/data
        name: db-data
  volumes:
    - name: db-data
      persistentVolumeClaim:
        claimName: db-data
