apiVersion: v1
kind: Pod
metadata:
  labels:
    app: knowhere-gpu-e2e
  namespace: knowhere-ci
spec:
  enableServiceLinks: false
  nodeSelector:
    app: knowhere
  containers:
  - name: main
    image: milvusdb/knowhere-gpu-e2e:amd64-ubuntu20.04-20220720-71e9862
    tty: true
    args: ["cat"]
    resources:
      requests:
        nvidia.com/gpu: 1
        memory: "8Gi"
        cpu: "8"
      limits:
        nvidia.com/gpu: 1
        memory: "8Gi"
        cpu: "8"
    volumeMounts:
    - mountPath: /home/data
      name: db-data
  volumes:
    - name: db-data
      nfs:
        server: 172.16.70.239
        path: /qa
