name: Cpplint

# This workflow is triggered on pushes or pull request to the repository.
on:
  push:
    # file paths to consider in the event. Optional; defaults to all.
    paths:
      - 'ci/**'
      - 'knowhere/**'
      - 'docker/build_env/**'
      - '.github/workflows/cpplint.yml'
      - docker-compose.yml
      - '!**.md'
      - '!ci/jenkins/**'
  pull_request:
    # file paths to consider in the event. Optional; defaults to all.
    paths:
      - 'ci/**'
      - 'knowhere/**'
      - '.github/workflows/cpplint.yml'
      - docker-compose.yml
      - '!**.md'
      - '!ci/jenkins/**'

jobs:
  centos:
    name: ${{ matrix.title }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        name:
          - cpplint
          - cpplint-gpu
        include:
          - name: cpplint
            service: cpplint
            title: Knowhere CppLint
          - name: cpplint-gpu
            service: cpplint-gpu
            title: Knowhere GPU Version CppLint
    steps:
      # This step checks out a copy of your repository.
      - name: Checkout Knowhere
        uses: actions/checkout@v2
      - name: Docker Pull
        shell: bash
        run: |
          docker-compose pull --ignore-pull-failures ${{ matrix.service }}
      - name: Docker Build
        shell: bash
        run: |
          docker-compose build ${{ matrix.service }}
      - name: Docker Run
        run: |
          docker-compose run ${{ matrix.service }}
      - name: Docker Push
        if: success() && github.event_name == 'push' && github.repository == 'milvus-io/knowhere'
        continue-on-error: true
        shell: bash
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USER }} \
                       -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker-compose push ${{ matrix.service }}
